site_name: Clean Pull Requests

pages:
  - Clean Git: index.md
  - Whys and Why Nots:
    - Why: why.md
    - Why not: whynot.md
    - Examples: examples.md
  - Things to Know:
    - A bit about Commits and Branches: commitsandbranches.md
    - Things to know: thingstoknow.md
    - Why do I care?: whydoicare.md
  - Techniques:
    - Summary: techniques.md
    - Amend: amend.md
    - Cherry Pick: cherrypick.md
    - Rebase: rebase.md
    - Interactive Rebase: interactiverebase.md

extra_css:
  - css/extra.css

plugins:
  - search
